import type { Product } from "@/types";

/* =========================================================
   CATÁLOGO
   // DEMO DATA - REPLACE BEFORE PRODUCTION
   Precios, stock, baterías y estados son ficticios.
   Para cambiar un precio: editar `priceUSD` del producto.
   Para usar renders reales: subir el archivo a /public/products/
   y agregar la ruta en `images` (ej. "/products/iphone-17-pro-max-silver.png").
   Con `images: []` se muestra el render placeholder de marca.
   ========================================================= */

export const products: Product[] = [
  {
    id: "p-01",
    slug: "iphone-17-pro-max-256-silver",
    modelId: "iphone-17-pro-max",
    name: "iPhone 17 Pro Max",
    condition: "nuevo",
    storageGB: 256,
    color: { name: "Silver", hex: "#DADAD6" },
    priceUSD: 1649,
    stock: "disponible",
    featured: true,
    releaseOrder: 1703,
    images: [],
  },
  {
    id: "p-02",
    slug: "iphone-17-pro-256-cosmic-orange",
    modelId: "iphone-17-pro",
    name: "iPhone 17 Pro",
    condition: "nuevo",
    storageGB: 256,
    color: { name: "Cosmic Orange", hex: "#E0762F" },
    priceUSD: 1449,
    stock: "disponible",
    featured: true,
    releaseOrder: 1702,
    images: [],
  },
  {
    id: "p-03",
    slug: "iphone-17-256-black",
    modelId: "iphone-17",
    name: "iPhone 17",
    condition: "nuevo",
    storageGB: 256,
    color: { name: "Black", hex: "#2A2A2C" },
    priceUSD: 1149,
    stock: "disponible",
    featured: true,
    releaseOrder: 1701,
    images: [],
  },
  {
    id: "p-04",
    slug: "iphone-16-pro-max-256-natural-titanium",
    modelId: "iphone-16-pro-max",
    name: "iPhone 16 Pro Max",
    condition: "nuevo",
    storageGB: 256,
    color: { name: "Natural Titanium", hex: "#BFB8AC" },
    priceUSD: 1399,
    stock: "disponible",
    featured: false,
    releaseOrder: 1603,
    images: [],
  },
  {
    id: "p-05",
    slug: "iphone-16-pro-128-black-titanium",
    modelId: "iphone-16-pro",
    name: "iPhone 16 Pro",
    condition: "nuevo",
    storageGB: 128,
    color: { name: "Black Titanium", hex: "#3B3B3A" },
    priceUSD: 1149,
    stock: "disponible",
    featured: false,
    releaseOrder: 1602,
    images: [],
  },
  {
    id: "p-06",
    slug: "iphone-16-128-ultramarine",
    modelId: "iphone-16",
    name: "iPhone 16",
    condition: "nuevo",
    storageGB: 128,
    color: { name: "Ultramarine", hex: "#5A6FE0" },
    priceUSD: 899,
    stock: "disponible",
    featured: false,
    releaseOrder: 1601,
    images: [],
  },
  {
    id: "p-07",
    slug: "iphone-15-pro-max-256-natural-titanium-seminuevo",
    modelId: "iphone-15-pro-max",
    name: "iPhone 15 Pro Max",
    condition: "seminuevo",
    storageGB: 256,
    color: { name: "Natural Titanium", hex: "#BDB6A9" },
    priceUSD: 999,
    stock: "disponible",
    featured: true,
    releaseOrder: 1503,
    images: [],
    used: { batteryHealth: 93, cosmetic: "excelente", functional: "100% funcional. Revisado y verificado." },
  },
  {
    id: "p-08",
    slug: "iphone-15-pro-128-blue-titanium-seminuevo",
    modelId: "iphone-15-pro",
    name: "iPhone 15 Pro",
    condition: "seminuevo",
    storageGB: 128,
    color: { name: "Blue Titanium", hex: "#4A5364" },
    priceUSD: 849,
    stock: "disponible",
    featured: false,
    releaseOrder: 1502,
    images: [],
    used: { batteryHealth: 91, cosmetic: "excelente", functional: "100% funcional. Revisado y verificado." },
  },
  {
    id: "p-09",
    slug: "iphone-15-128-black-seminuevo",
    modelId: "iphone-15",
    name: "iPhone 15",
    condition: "seminuevo",
    storageGB: 128,
    color: { name: "Black", hex: "#35373A" },
    priceUSD: 679,
    stock: "disponible",
    featured: false,
    releaseOrder: 1501,
    images: [],
    used: { batteryHealth: 89, cosmetic: "muy-bueno", functional: "100% funcional. Revisado y verificado." },
  },
  {
    id: "p-10",
    slug: "iphone-14-pro-128-space-black-seminuevo",
    modelId: "iphone-14-pro",
    name: "iPhone 14 Pro",
    condition: "seminuevo",
    storageGB: 128,
    color: { name: "Space Black", hex: "#2F2E30" },
    priceUSD: 699,
    stock: "disponible",
    featured: false,
    releaseOrder: 1402,
    images: [],
    used: { batteryHealth: 88, cosmetic: "muy-bueno", functional: "100% funcional. Revisado y verificado." },
  },
  {
    id: "p-11",
    slug: "iphone-14-128-midnight-seminuevo",
    modelId: "iphone-14",
    name: "iPhone 14",
    condition: "seminuevo",
    storageGB: 128,
    color: { name: "Midnight", hex: "#262B33" },
    priceUSD: 549,
    stock: "disponible",
    featured: false,
    releaseOrder: 1401,
    images: [],
    used: { batteryHealth: 87, cosmetic: "muy-bueno", functional: "100% funcional. Revisado y verificado." },
  },
  {
    id: "p-12",
    slug: "iphone-13-128-midnight-seminuevo",
    modelId: "iphone-13",
    name: "iPhone 13",
    condition: "seminuevo",
    storageGB: 128,
    color: { name: "Midnight", hex: "#232831" },
    priceUSD: 449,
    stock: "disponible",
    featured: false,
    releaseOrder: 1301,
    images: [],
    used: { batteryHealth: 86, cosmetic: "bueno", functional: "100% funcional. Revisado y verificado." },
  },
];
